%\VignetteIndexEntry{spbtest3}
%\VignetteKeywords{spbtest3}
%\VignettePackage{spbtest3}
\documentclass{article}

\title{An Introduction to the spbtest3 Package}
\author{Lori Shepherd}
\date{\today}

\begin{document}

\maketitle

\tableofcontents

\section{Introduction}
A test package 

<<eval=TRUE>>=
# workflow and data experiment get 4800 sec (80 min)
library('devtools')
Sys.sleep(1)
@ 

\end{document}
