%\VignetteIndexEntry{A Test Vignette}
%\VignettePackage{spbtest3}

\documentclass[10pt]{article}

\title{A Test Vignette}
\author{Lori Shepherd}
\date{\today}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

\section{Introduction}
Needed a test vignette

\subsection{test spbtest3}
So creating a test vignette

\subsection{subsection}
to run to make sure 

\section{Methods}
can run without error

\section{R session information}

<<>>=
sessionInfo()
@ 

\end{document}


